name: "CI"
on:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master
jobs:
  windows-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/github-script@v3
        id: context
        with:
          script: console.log(context)


