name: "CI"
on:
  push:
    # Comment out this section to enable testing of all branches.
    branches:
      - master
  pull_request:
    paths-ignore: ['**.adoc']
    branches-ignore: ['future-doc']
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2
      - uses: actions/github-script@v3
        with:
          script: |
            const exec = require('util').promisify(require('child_process').exec);
            const downloadScript = require(`${process.env.GITHUB_WORKSPACE}/.github/workflows/util.js`);
            const script = await downloadScript(github, io, context, "hello");
            let out1 = await exec(script);
            console.log(out1.stdout);






